### ISSUE TITLE
Security page of a certain Nix issue

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#10]
The security page of a certain Nix issue should:

- [x] be accessible via `website.tld/$tracking`
- [x] informs about the current status: awaiting-mitigation, mitigation-in-progress, mitigated, wontfix on each supported channel.
- [x] list all maintainers, grouped by package
- [x] list all known vulnerabilities
  - [x] grouped by package

For maintainers (or more):
- change status.
- performs any operations: bump the package in that channel (unstable or stable X), add/remove a known vulnerability as a new PR.

For security team:
- admin access.

**Comment by RaitoBezarius** [comment]
That might be overkill because it will store the whole NixIssue information rather than just an activity log of "has changed X to Y", "has added X", etc. 
But I guess that's an option.

**Comment by alejandrosame** [comment]
Check #101 for the activity log setup. Like the message says, for now it tracks all changes to NixpkgsIssue model, but it's trivial to add per-field tracking once the model has stabilized.

**Comment by fricklerhandwerk** [comment]
Superseded by https://github.com/Nix-Security-WG/nix-security-tracker/issues/1
