### ISSUE TITLE
[Tracking issue] User story "Maintainers"

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#2]
This is a tracking issue for the user story for maintainers of a package in Nixpkgs.

### Persona story (desired situation)

<details><summary>Current situation</summary>

As a maintainer of nixpkgs, I **may** be subscribed to a mailing list or a notification feed of the projects I am maintaining.

I may be notified in the Matrix room: [matrix.to/#/#security:nixos.org](https://matrix.to/#/#security:nixos.org) about security vulnerabilities by the security team, or I may notice them and take care of them. It may also happen as part of a fix proposed by the security community.

I ensure that the proposed fix is working as expected with respect to package capabilities, conduct the due diligence on whether this fixes the security vulnerability, and offer any valuable input to the security community on the situation.

I also ensure that PRs pertaining to that fix are backported to any supported stable channels of Nixpkgs, including NixOS, and offer my input if the change could be too breaking and may do the work to cherry-pick the relevant commits as an alternative fix to stable channels.

</details>

As a maintainer of Nixpkgs
- [ ] I want to be notified when my package suffers from known vulnerabilities that are tracked by the security team.
  - https://github.com/Nix-Security-WG/nix-security-tracker/issues/9
- [ ] I want to be notified when fixes landed in all stable channels I should care about
- [ ] I want to know  whether there's further input that is expected from my side, like a fix, a comment.

I would like to manage the ongoing security issues pertaining to the package I maintain by being able to:

- [ ] Confirm a security issue
- [ ] Communicate that I am working on a fix
  - this could be implemented cheaply by assigning oneself to a linked GitHub issue 
- https://github.com/Nix-Security-WG/nix-security-tracker/issues/138
- [ ] Open a GitHub issue with relevant information pre-filled
  
If possible, I would like to have easy remediation features when possible:

- [ ] #218
- [ ] #219
- [ ] #220

In the future, this can have interesting synergy with https://github.com/NixOS/rfcs/pull/127 (being implemented).

### Proof of concept

- Offering a maintenance UI on a security issue as a maintainer of said package, e.g. permissions based on `meta.maintainers` and GitHub linkage: security team always have the last word and maintainers comes after: https://github.com/Tom-Hubrecht/nix-security-tracker/issues/10
- Offering a set of actions to open PRs inside nixos/nixpkgs on behalf of a maintainer or a security team member: https://github.com/Tom-Hubrecht/nix-security-tracker/issues/7
- Sending reminders based on the absence of status update to maintainer or security team member subscribing to certain events (absence of remediation after a while is yet another an event): https://github.com/Tom-Hubrecht/nix-security-tracker/issues/9
- Override some guessed presets for notifications for a user, e.g. I would like to be notified by X or Y or at this security@raitobezarius.org email address: https://github.com/Tom-Hubrecht/nix-security-tracker/issues/9

**Comment by fricklerhandwerk** [comment]
Closing this tracking issue in favor of [milestones](https://github.com/Nix-Security-WG/nix-security-tracker/milestones).
